In [13]:
import numpy as np

a = np.array([[[
          [1,5,7,2,3],
          [2,3,2,5,6],
          [9,3,2,4,3],
          [5,1,0,0,3],
          [2,3,2,4,3]]]])
print (np.max(a[0:3,0:3]))
pooling_shape = 2
stride = 2
_,_,x, y = a.shape
x_o = (x - pooling_shape)/stride +1
y_o = (y - pooling_shape)/stride +1
out_put = np.zeros((int(x_o),int(y_o)))
#print(out_put)
print(a.shape)
 

9
(1, 1, 5, 5)


array([[[[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]]]]]])

In [14]:
from Layers.Pooling import Pooling

p_layer = Pooling(stride, pooling_shape)
p_layer.forward(a)

TypeError: cannot unpack non-iterable int object

In [ ]:
m=n = 0
for i in range(0,x,stride):
    if i+pooling_shape <= x :
        n = 0
        for j in range(0,y,stride):
            if j+pooling_shape <= y:
                

                out_put[m,n] = np.max(a[i:i+pooling_shape,j:j+pooling_shape])
                n+=1
        m+=1


print(out_put)

[[5. 7.]
 [9. 4.]]


In [ ]:
a = np.unravel_index(1621, (6,7,8,9))
a

(3, 1, 4, 1)

In [ ]:
a = np.array([[6,3],
              [7,2]])
b = np.array([[6,4,3],
              [2,5,4],
              [7,1,2]])
a_input = np.array([[6,5,3,0],
                    [2,3,1,2],
                    [4,1,0,0],
                    [7,1,2,2]])
a_stride = 2 

a_input = np.array([[6,4,3,0],
                    [0,1,1,2],
                    [2,1,5,0],
                    [6,1,2,2]])

In [ ]:

c = a_input==np.max(a_input)
print(np.multiply(a_input,c))   


[[6 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [6 0 0 0]]


In [ ]:

input_tensor = np.array([
          [1,5,7,2,3],
          [2,3,2,5,6],
          [9,3,2,4,3],
          [5,1,0,0,3],
          [2,3,2,4,3]])

erro_tensor = np.array(
                [[5, 7],
                [9, 4]])
pooling_shape = 2
stride = 2

x_input, y_input = input_tensor.shape 
out_put = np.zeros((x_input,y_input))


In [ ]:
x_error, y_error = erro_tensor.shape 
for i in range(x_error):
    for j in range(y_error):
        input_tensor_p = input_tensor[i*stride:i*stride +pooling_shape, j*stride:j*stride +pooling_shape]
        mask = input_tensor_p == np.max(input_tensor_p)
        #print("next")
        out_put[i*stride:i*stride +pooling_shape, j*stride:j*stride +pooling_shape] = np.multiply(erro_tensor[i,j],mask)
        #print(out_put)

    print("first row")

print(out_put)


first row
first row
[[0. 5. 7. 0. 0.]
 [0. 0. 0. 0. 0.]
 [9. 0. 0. 4. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [2]:
con_shep = (3, 3)
n_kernels = 5

w_shape = (n_kernels, *con_shep)
w_shape

(5, 3, 3)

In [4]:
from Layers.Base import BaseLayer
layer1 = BaseLayer()
layer2 = BaseLayer()
layer1.trainable = True

from Optimization.Loss import CrossEntropyLoss
from Optimization.Optimizers import Sgd

opt_sgd = Sgd(.1)
loss_ent = CrossEntropyLoss()

In [5]:
class Neuralnetwork :
    def __init__(self) :
        self.layers = list()
        self.optimizer = None 
        self.loss = None 
    
    def set_optimizer(self,optimizer):
        self.optimizer = optimizer

    def set_loss(self,loss):
        self.loss = loss 
    
    def add_layer(self,layer):
        self.layers.append(layer)
    
    def print_info(self):
        print("opt -- ", self.optimizer)
        print("loss -- ", self.loss)
        for i in range(len(self.layers)):
            print("layer {} -- ".format(i), self.layers[i])
    

In [6]:
net = Neuralnetwork()
net.set_optimizer(opt_sgd)
net.set_loss(loss_ent)
net.add_layer(layer1)
net.add_layer(layer2)

net.print_info()

opt --  <Optimization.Optimizers.Sgd object at 0x000002EB3B13C820>
loss --  <Optimization.Loss.CrossEntropyLoss object at 0x000002EB3B13CEE0>
layer {i} --  <Layers.Base.BaseLayer object at 0x000002EB3B13CF10>
layer {i} --  <Layers.Base.BaseLayer object at 0x000002EB3B13CB50>
